name: docker-builder
on:
    push:
        tags:
            - "**"

jobs:
    build-image:
        if: "! endsWith(github.ref_name, '[nobuild]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            # - name: Update CHANGELOG
            #   id: changelog
            #   uses: requarks/changelog-action@v1
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            #       tag: ${{ github.ref_name }}

            # - name: Commit CHANGELOG.md
            #   uses: stefanzweifel/git-auto-commit-action@v4
            #   with:
            #       branch: main
            #       commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
            #       file_pattern: CHANGELOG.md

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract client version from tag
              id: extract_version
              run: echo "CLIENTVERSION=$(echo '${{ github.ref_name }}' | sed 's/[ _-].*$//')" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64,linux/riscv64
                  push: true
                  build-args: |
                      CLIENTVERSION=${{ env.CLIENTVERSION }}
                  tags: |
                      werecatf/hidemevpn:latest
                      werecatf/hidemevpn:${{ env.CLIENTVERSION }}
                      ghcr.io/werecatf/hidemevpn:latest
                      ghcr.io/werecatf/hidemevpn:${{ env.CLIENTVERSION }}
